#!/bin/bash

IFS=$'\n'

# Testing git
# Auth Test

# Colors
GREEN='\033[0;32m'
RED='\033[0;31m'
ORANGE='\033[0;33m'
NC='\033[0;0m'

SUPPORTED_FORMATS='\.mp4$|\.m4a$|\.mov$|\.mp3$|\.wav$'
VIDEOPATH="$*"

# Set videopath equal to current dir if none are specified
if [ -z "$VIDEOPATH" ]; then VIDEOPATH="."; fi

if [ ! -d "$VIDEOPATH" ]; then echo -e $'\n' "${RED}ERROR:${NC} The directory $VIDEOPATH could not be found" $'\n'; exit 1; fi

SERVICE="omxplayer"
TRACK_NUM=0
TRACK_AMOUNT=$(ls $VIDEOPATH | egrep $SUPPORTED_FORMATS | wc -l)

# Some error detection

if ! $SERVICE &> /dev/null; then echo -e $'\n' "${RED}ERROR:${NC} Missing dependency: omxplayer" $'\n'; exit 1; fi
if [[ $TRACK_AMOUNT = 0  ]]; then echo -e $'\n' "${RED}ERROR:${NC} No compatible files were found in the directory" $'\n'; exit 1; fi

while true; do
  if ps ax | grep -v grep | grep $SERVICE > /dev/null; then sleep 2;

  else
    for entry in $VIDEOPATH/*;
    do
      clear

      if ! mp3info &> /dev/null; then
        echo -e "${ORANGE}WARNING:${NC} Missing dependency: mp3info" $'\n'
      fi

      if [ "$TRACK_NUM" = "$TRACK_AMOUNT" ]; then let "TRACK_NUM=0"; fi

      let "TRACK_NUM+=1"

      echo -n "Currently Playing: "
      if mp3info -p %t $entry &> /dev/null; then echo $(mp3info -p %t $entry); else echo $(basename $entry); fi

      echo "Track " $TRACK_NUM " / " $TRACK_AMOUNT $'\n'

      echo -n "Artist: "
      if mp3info -p %a $entry &> /dev/null; then echo $(mp3info -p %a $entry); else echo "Unknown"; fi
      echo -n "Released: "
      if mp3info -p %y $entry &> /dev/null; then echo $(mp3info -p %y $entry); else echo "Unknown"; fi
      echo -n "Album: "
      if mp3info -p %l $entry &> /dev/null; then echo $(mp3info -p %l $entry); else echo "Unknown"; fi

      omxplayer $entry > /dev/null
    done
  fi
done
